version: "3.8"
services:
    manager-database:
        image: mysql:latest
        environment:
            MYSQL_DATABASE: manager
            MYSQL_ROOT_PASSWORD: secret
        ports:
            - "3306:3306"
    database-explorer:
        image: phpmyadmin:latest
        restart: always
        ports:
            - 8036:80
        environment:
            PMA_ARBITRARY: 1
            PMA_HOST: manager-database
            PMA_PORT: 3306
            PMA_USER: root
            PMA_PASSWORD: secret
